---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 91
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-63
  scss-lint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - config/initializers/**/*
exclude_paths:
- config/
- db/
- node_modules/
- script/
- vendor/
- public/assets/
- public/mobile_app/
- app/assets/javascripts/goldencobra/html_editors/ckeditor/
- app/assets/javascripts/vendor/
- app/assets/stylesheets/vendor/
- app/assets/stylesheets/_slimbox_overwrite.scss
- app/assets/stylesheets/application_old.scss
- app/assets/javascripts/application_old.js
- tmp/
- log/
- docs
- doc_assets
- .rubocop.yml
- .codeclimate.yml
- .scss-lint.yml
- .eslintrc
- .eslintrc.json
- .csslintrc
