version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    command: bin/delayed_job run
    environment:
      SVA_COMMUNITY: saas-staging
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    command: bin/start-cron.sh
    environment:
      SVA_COMMUNITY: saas-staging
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    environment:
      SVA_COMMUNITY: saas-staging
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  unicorn:
  assets:
  unused:

configs:
  mainserver-common-master-key:
    external: true
  smart-village-app-mainserver-nginx-conf:
    external: true

networks:
  public:
    external: true
  sva-redis-server:
    external: true
  saas-database-service-staging:
    external: true
