version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas
    command: bin/delayed_job run
    environment:
      SVA_COMMUNITY: saas
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - $VOLUME_LOCALTIME
      - unicorn:/unicorn
      - assets:/assets
    depends_on: [db]
    deploy:
      restart_policy:
        condition: on-failure

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas
    command: bin/start-cron.sh
    environment:
      SVA_COMMUNITY: saas
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - $VOLUME_LOCALTIME
      - unicorn:/unicorn
      - assets:/assets
    depends_on: [db]
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas
    environment:
      SVA_COMMUNITY: saas
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on: [app]
    networks: [default, public]
    configs:
      - source: smart-village-app-mainserver-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - $VOLUME_LOCALTIME
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.frontend.rule=Host:smartvillage.app
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  unicorn:
  assets:
  unused:

configs:
  mainserver-common-master-key:
    external: true
  smart-village-app-mainserver-nginx-conf:
    external: true

networks:
  public:
    external: true
  sva-redis-server:
    external: true
  saas-database-service:
    external: true
