version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    networks:
      - saas-smart-village-staging
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    networks:
      - saas-smart-village-staging
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname == ${NODENAME}
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        traefik.docker.network: public
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 1

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver:saas-staging
    networks:
      - public
      - saas-smart-village-staging
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.community.frontend.rule: HostRegexp:{subdomain:[a-zA-Z-_]+}.staging-server.smart-village.app
        traefik.admin.frontend.rule: Host:staging-server.smart-village.app

networks:
  adminer:
    external: true
  public:
    external: true
  saas-smart-village-staging:
    external: true
