version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    networks:
      - default
      - logs
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    networks:
      - default
      - public
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname == ${NODENAME}
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        traefik.docker.network: public
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    networks:
      - default
      - logs
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

  nginx:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.frontend.rule: Host:server.${DOMAINNAME}.smart-village.app

  db:
    networks:
      default:
      adminer:
        aliases:
          - ${PROJECT}-mainserver
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  adminer:
    external: true
  logs:
    external: true
  public:
    external: true
