require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/municipalities", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Municipality. As you add validations to Municipality, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Municipality.create! valid_attributes
      get municipalities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      municipality = Municipality.create! valid_attributes
      get municipality_url(municipality)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_municipality_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      municipality = Municipality.create! valid_attributes
      get edit_municipality_url(municipality)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Municipality" do
        expect {
          post municipalities_url, params: { municipality: valid_attributes }
        }.to change(Municipality, :count).by(1)
      end

      it "redirects to the created municipality" do
        post municipalities_url, params: { municipality: valid_attributes }
        expect(response).to redirect_to(municipality_url(Municipality.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Municipality" do
        expect {
          post municipalities_url, params: { municipality: invalid_attributes }
        }.to change(Municipality, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post municipalities_url, params: { municipality: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested municipality" do
        municipality = Municipality.create! valid_attributes
        patch municipality_url(municipality), params: { municipality: new_attributes }
        municipality.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the municipality" do
        municipality = Municipality.create! valid_attributes
        patch municipality_url(municipality), params: { municipality: new_attributes }
        municipality.reload
        expect(response).to redirect_to(municipality_url(municipality))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        municipality = Municipality.create! valid_attributes
        patch municipality_url(municipality), params: { municipality: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested municipality" do
      municipality = Municipality.create! valid_attributes
      expect {
        delete municipality_url(municipality)
      }.to change(Municipality, :count).by(-1)
    end

    it "redirects to the municipalities list" do
      municipality = Municipality.create! valid_attributes
      delete municipality_url(municipality)
      expect(response).to redirect_to(municipalities_url)
    end
  end
end
