require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe StaticContentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StaticContent. As you add validations to StaticContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  let(:valid_session) { {} }

  describe "GET #index" do

    context "when user is logged out" do
      before do
        get :index
      end

      it { is_expected.to redirect_to new_user_session_path }
    end

    context "when user is signed in" do
      login_user

      before do
        get :index
      end

      it { is_expected.to respond_with :not_found }
      it { expect(response.body).to include("not allowed") }
    end

    context "when admin is signed in" do
      login_admin
      render_views

      it "returns a success response" do
        get :index, params: {}, session: valid_session
        expect(response.status).to eq(200)
      end

      it "should include static contents" do
        name1 = 'StaticContentABC'
        name2 = 'StaticContentXYZ'
        FactoryBot.create(:static_content, name: name1)
        FactoryBot.create(:static_content, name: name2)
        get :index, params: {}

        expect(response.body).to include(name1)
        expect(response.body).to include(name2)
      end
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      static_content = StaticContent.create! valid_attributes
      get :show, params: {id: static_content.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      static_content = StaticContent.create! valid_attributes
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      static_content = StaticContent.create! valid_attributes
      get :edit, params: {id: static_content.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StaticContent" do
        expect {
          post :create, params: {static_content: valid_attributes}, session: valid_session
        }.to change(StaticContent, :count).by(1)
      end

      it "redirects to the created static_content" do
        post :create, params: {static_content: valid_attributes}, session: valid_session
        expect(response).to redirect_to(StaticContent.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {static_content: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested static_content" do
        static_content = StaticContent.create! valid_attributes
        put :update, params: {id: static_content.to_param, static_content: new_attributes}, session: valid_session
        static_content.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the static_content" do
        static_content = StaticContent.create! valid_attributes
        put :update, params: {id: static_content.to_param, static_content: valid_attributes}, session: valid_session
        expect(response).to redirect_to(static_content)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        static_content = StaticContent.create! valid_attributes
        put :update, params: {id: static_content.to_param, static_content: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested static_content" do
      static_content = StaticContent.create! valid_attributes
      expect {
        delete :destroy, params: {id: static_content.to_param}, session: valid_session
      }.to change(StaticContent, :count).by(-1)
    end

    it "redirects to the static_contents list" do
      static_content = StaticContent.create! valid_attributes
      delete :destroy, params: {id: static_content.to_param}, session: valid_session
      expect(response).to redirect_to(static_contents_url)
    end
  end

end
